data:
  data:
  train_path: "C:/Users/estre/MLops/churn/develop/data/train.csv"
  test_path: "C:/Users/estre/MLops/churn/develop/data/test.csv"

  #train_path: "./data/train.csv"
  #test_path: "./data/test.csv"

train:
  test_size: 0.2
  random_state: 42
  shuffle: true

model:
  name: LogisticRegression
  params:
    penalty: l2        # Regularización (l1, l2, elasticnet o none)
    C: 1.0             # Inverso de la fuerza de regularización
    solver: lbfgs      # Optimizador (lbfgs, saga, etc.)
    max_iter: 100      # Máximo de iteraciones para la convergencia
  store_path: models/

  # name: GradientBoostingClassifier
  # params:
  #   max_depth: null
  #   n_estimators: 10
  # store_path: models/

  # name: RandomForestClassifier
  # params:
  #   n_estimators: 50
  #   max_depth: 10
  #   random_state: 42
  # store_path: models/